[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[WhiteElo ""]
[Black "?"]
[BlackElo ""]
[Result "0-1"]
[Annotator "Crafty v19.3"]
{annotating only white moves.}
{using a scoring margin of -1.00 pawns.}
{search time limit is 1.00}

  1.     Nc3
                ({9:+0.03}  1. Nc3 d5 2. d4 Nf6 3. Nf3 Bf5 4. Bf4 Nbd7 5. e3 $10)
                ({9:+0.03}  1. e4 Nc6 2. Nf3 Nf6 3. Nc3 d5 4. e5 Ne4 5. d4 Nxc3 6. bxc3 $10)

  1.     ...      d5

       0-1 


